CREATE OR REPLACE WAREHOUSE CHINOOK_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE OR REPLACE DATABASE CHINOOK_DB;
CREATE OR REPLACE SCHEMA CHINOOK_DB.CHINOOK_SCHEMA;
CREATE OR REPLACE SCHEMA CHINOOK_DB.DW;
CREATE OR REPLACE SCHEMA CHINOOK_DB.STAGE;
CREATE OR REPLACE ROLE CHINOOK_ROLE;

CREATE OR REPLACE USER CHINOOK_USER 
    PASSWORD='DAMG7370FALL2025' 
    DEFAULT_ROLE=CHINOOK_ROLE 
    DEFAULT_WAREHOUSE=CHINOOK_WH;

GRANT ROLE CHINOOK_ROLE TO ROLE ACCOUNTADMIN;
GRANT ROLE CHINOOK_ROLE TO USER CHINOOK_USER;

GRANT USAGE ON WAREHOUSE CHINOOK_WH TO ROLE CHINOOK_ROLE;
GRANT OPERATE ON WAREHOUSE CHINOOK_WH TO ROLE CHINOOK_ROLE;

GRANT USAGE ON DATABASE CHINOOK_DB TO ROLE CHINOOK_ROLE;
GRANT USAGE ON SCHEMA CHINOOK_DB.CHINOOK_SCHEMA TO ROLE CHINOOK_ROLE;
GRANT USAGE ON SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;
GRANT USAGE ON SCHEMA CHINOOK_DB.STAGE TO ROLE CHINOOK_ROLE;

-- Grant permissions on STAGE schema tables
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CHINOOK_DB.STAGE TO ROLE CHINOOK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA CHINOOK_DB.STAGE TO ROLE CHINOOK_ROLE;

-- Grant permissions on DW schema tables
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;

-- Grant permissions on sequences
GRANT USAGE ON ALL SEQUENCES IN SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;

-- Grant CREATE TABLE privileges
GRANT CREATE TABLE ON SCHEMA CHINOOK_DB.STAGE TO ROLE CHINOOK_ROLE;
GRANT CREATE TABLE ON SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;

--------------
-- Grant ALL privileges on STAGE schema (not just USAGE)
GRANT ALL PRIVILEGES ON SCHEMA CHINOOK_DB.STAGE TO ROLE CHINOOK_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;

-- Ensure role can create and modify tables
GRANT CREATE TABLE ON SCHEMA CHINOOK_DB.STAGE TO ROLE CHINOOK_ROLE;
GRANT CREATE TABLE ON SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;

-- Grant full permissions on existing tables
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA CHINOOK_DB.STAGE TO ROLE CHINOOK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;

-- Grant permissions on future tables
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA CHINOOK_DB.STAGE TO ROLE CHINOOK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;

-- Also grant for DW schema since you'll likely need it
GRANT ALL PRIVILEGES ON SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA CHINOOK_DB.DW TO ROLE CHINOOK_ROLE;

CREATE FILE FORMAT IF NOT EXISTS CHINOOK_DB.STAGE.parquet_format 
    TYPE = 'PARQUET' 
    COMPRESSION = 'SNAPPY';
    
