WITH aggsales AS (
    SELECT 
        cd.CUSTOMER_KEY,
        i.INVOICE_ID AS INVOICE_ID,
        i.SALE_DATE AS SALE_DATE,
        SUM(il.QUANTITY * il.UNIT_PRICE) AS TOTAL_SALE_AMT
    FROM DW.INVOICE_DIM i
    JOIN DW.INVOICELINE_DIM il ON i.INVOICE_ID = il.INVOICE_ID
    JOIN DW.CUSTOMER_DIM cd ON cd.CUSTOMER_ID = i.CUSTOMER_ID
    GROUP BY 
        i.INVOICE_ID,
        cd.CUSTOMER_KEY,
        i.SALE_DATE
)
SELECT 
    ROW_NUMBER() OVER (ORDER BY INVOICE_ID) AS SALES_KEY,
    CUSTOMER_KEY,
    INVOICE_ID,
    -- SALE_DATE,
    dd.DATE_KEY AS DATE_DIM_KEY,
    td.TIME_KEY AS TIME_DIM_KEY,
    TOTAL_SALE_AMT,
    'ADF_PIPELINE' AS SOURCE_ID,
    CURRENT_TIMESTAMP() AS DATE_TO_WAREHOUSE
FROM aggsales a
JOIN DW.DATE_DIM dd ON dd.FULL_DATE = DATE(a.SALE_DATE)
JOIN DW.TIME_DIM td ON td.TIME_24_HR = TO_CHAR(a.SALE_DATE, 'HH24:MI')
WHERE NOT EXISTS (
    SELECT 1
    FROM DW.SALES_FACT sf
    WHERE sf.INVOICE_ID = a.INVOICE_ID
);

